In [1]:
import yfinance as yf

In [2]:
#### FECHAS
import datetime as dt
#start =dt.datetime(2000,1,1)
start =dt.datetime.today() - dt.timedelta(days=500)    #un año tiene 250 sesiones.
#end = dt.datetime(2019,10,1)
end= dt.datetime.today()  - dt.timedelta(days=1)        #Quito hoy para no ver el valor al ejecutar antes del cierre
#end = '2022-9-15'  ##solo para pruebas ESte dia tengo varias señales

In [3]:
df = yf.download('MSTF',start, end)

[*********************100%***********************]  1 of 1 completed


In [8]:
import datetime
import pandas_datareader as pdr
import pylab as plt
start=datetime.datetime(2010,1,1)
end=datetime.datetime(2021,12,31)
df = pdr.DataReader('ticker=SAN.MC','econdb',start,end)

In [5]:
df.head()

Empty DataFrame
Columns: [SAN.MC]
Index: []

In [6]:
df1=pdr.eurostat.EurostatReader('SAN')

In [7]:
print(df1)


## dataLoger


In [13]:
import pandas as pd
df2 = pd.DataFrame(columns=['instrumento', 'divergencia', 'fecha'])

In [16]:
instrumento = 'san'

In [17]:
df2 = df2.append({'instrumento': instrumento, 'divergencia':'yes', 'gender':'Female'}, ignore_index=True)

C:\Users\INNOVACION\AppData\Local\Temp\ipykernel_44492\21890575.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append({'instrumento': instrumento, 'divergencia':'yes', 'gender':'Female'}, ignore_index=True)


In [18]:
df2

instrumento divergencia fecha  gender
0         san         yes   NaN  Female

In [1]:
import logging
logging.warning('Watch out!')  # will print a message to the console
logging.info('I told you so')  # will not print anything

In [4]:
import logging
logging.basicConfig(filename='test.txt', level=logging.DEBUG,encoding='utf-8',force=True)
                    ##format='%(asctime)s:%(levelname)s:%(message)s')

logging.warning('esto es una alerta')



In [1]:

from sklearn import preprocessing
import numpy as np
X = np.array([[ 1., -1.,  2.],[ 2.,  0.,  0.],[ 0.,  1., -1.]])
scaler= preprocessing.MinMaxScaler(feature_range=(-1, 1)).fit(X)
X_scaled = scaler.transform(X)
print(X)
print(X_scaled)
X1=scaler.inverse_transform(X_scaled)
print(X1)
print(X1[0, -1])
 

[[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]
[[ 0.         -1.          1.        ]
 [ 1.          0.         -0.33333333]
 [-1.          1.         -1.        ]]
[[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]
2.0
